### ISSUE TITLE
Amelioration interface Markdown

### ISSUE THREAD

**Issue by Kae134** [Oomaxime/MarkdownXP#15]
Une issue pour ajouter les modifications en plus sur le markdown : 
- Reparation du css
- Ajout de fonctionnalites non-push sur l'ancienne issue
- ...

**Comment by Oomaxime** [comment]
Essaye de donner plus de détail, il faut être plus précis. Même si c'est pour toi, imagine que tu va donner la tâche a quelqu'un et que ces seuls infos serons cette issue.
